### ISSUE TITLE
Processor for uploading output CSV into CKAN

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/datapackage-pipelines-ckan#1]
### Description

Create a `dump.to_ckan_resource` processor that can take the output of a pipeline and upload it to CKAN. For this it will use the CKAN API (action `resource_create`). Parameters will include dataset id, format (CSV or JSON?). It will need to ingest a CKAN API key somehow.

### Tasks

- [ ] Implement processor
- [ ] Documentation
- [ ] Tests

### Estimate

3

**Comment by brew** [comment]
Closed in favour of #6.
