### ISSUE TITLE
Processor for storing pipeline output into CKAN DataStore

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/datapackage-pipelines-ckan#2]
### Description

Create a `dump.to_ckan_datastore` processor that can take the output of a pipeline and upload it to CKAN. For this it will use the CKAN API (action `datastore_create`). Parameters will include dataset id (or resource rather). It will need to ingest a CKAN API key somehow.

### Tasks

- [x] Implement processor
- [x] Documentation
- [x] Tests

### Estimate

4

**Comment by brew** [comment]
In discussion with @amercader we decided to look into implementing this based around a new [tableschema storage plugin](https://github.com/frictionlessdata/tableschema-py#storage), tableschema-datastore. There are further applications possible, including useful integration with CKAN itself.

**Comment by brew** [comment]
Rather than a separate processor, I'd propose to have datastore functionality integrated with the existing `ckan.dump.to_ckan` processor, determined by a parameter flag: `push_resources_to_datastore` or similar.
